import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Works from "../components/Works";
import About from "../components/About";
import Marquee from "../components/Marquee";
import Footer from "../components/Footer";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Ezomon GLory</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className=''>
				<Header />
				<div className='px-[20px] md:px-[50px] lg:px-[80px]'>
					<div id="hero" >
                    <Hero />
                    </div>
					<div id="works" >
                    <Works />
                    </div>
					<div id="about" >
                    <About />
                    </div>
				</div>
				<div id="contact" >
                <Marquee />
                </div>
				<div className='px-[20px] md:px-[50px] lg:px-[80px] '>
					<div className="mb-[2rem] mt-[32px] md:mt-[80px]">
						<Footer />
						</div> 
				</div>
			</main>
		</div>
	);
}
